BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET TRANSACTION READ WRITE;

-- Bloqueia a linha da sala para garantir que outra transação não altere ao mesmo tempo
SELECT QUANTIDADE_ATUAL, QUANTIDADE_MAX 
FROM SALA 
WHERE NUMERO_SALA = 101 
FOR UPDATE;

-- Atualiza a quantidade atual se ainda houver espaço
UPDATE SALA 
SET QUANTIDADE_ATUAL = QUANTIDADE_ATUAL + 1 
WHERE NUMERO_SALA = 101 AND QUANTIDADE_ATUAL < QUANTIDADE_MAX;

-- Insere o aluno
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) 
VALUES ('A031', 'Paulo Henrique', 21, 101);

COMMIT;
