SET TRANSACTION READ WRITE;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT QUANTIDADE_ATUAL, QUANTIDADE_MAX FROM SALA WHERE NUMERO_SALA=101 FOR UPDATE;
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A031', 'João Manoel', 24, 101);
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A032', 'Cristiano Alves', 22, 101);
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A033', 'Gilberto Arlan', 23, 101);
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A034', 'Israel Mario', 22, 101);
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A035', 'Tiago Arthur', 24, 101);
UPDATE SALA SET QUANTIDADE_ATUAL = QUANTIDADE_ATUAL + 5 WHERE NUMERO_SALA = 101;
