BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET TRANSACTION READ WRITE;

-- Bloqueia a tabela SALA em modo exclusivo para impedir conflitos
LOCK TABLE SALA IN EXCLUSIVE MODE;

UPDATE SALA SET QUANTIDADE_MAX = 35 WHERE NUMERO_SALA = 101;
COMMIT;
