SET TRANSACTION READ WRITE;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
UPDATE SALA SET QUANTIDADE_MAX = 17 WHERE NUMERO_SALA = 101;
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A036', 'Marina Souza', 21, 101);
INSERT INTO ALUNO (MATRICULA_ALUNO, NOME_ALUNO, IDADE_ALUNO, NUMERO_SALA) VALUES ('A037', 'Paulo Henrique', 22, 101);
UPDATE SALA SET QUANTIDADE_ATUAL = QUANTIDADE_ATUAL + 2 WHERE NUMERO_SALA = 101;



