SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET TRANSACTION READ WRITE;

-- Bloqueia as associações da sala 102 para atualização
SELECT * FROM SALA_PROFESSOR WHERE NUMERO_SALA = 102 FOR UPDATE;

-- Remove professor P004 da sala 102
DELETE FROM SALA_PROFESSOR WHERE ID_PROFESSOR = 'P004' AND NUMERO_SALA = 102;

-- Insere novo professor P002 na sala 102
INSERT INTO SALA_PROFESSOR (ID_PROFESSOR, NUMERO_SALA) VALUES ('P002', 102);

