BEGIN;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET TRANSACTION READ WRITE;

-- Bloqueia o aluno para evitar alterações concorrentes
SELECT * FROM ALUNO 
WHERE MATRICULA_ALUNO = 'A002' 
FOR UPDATE;

-- Deleta o aluno
DELETE FROM ALUNO 
WHERE MATRICULA_ALUNO = 'A002';

-- Decrementa a quantidade atual da sala
UPDATE SALA 
SET QUANTIDADE_ATUAL = QUANTIDADE_ATUAL - 1 
WHERE NUMERO_SALA = 101;

COMMIT;
