SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT COUNT(*) AS total_professores101 FROM SALA_PROFESSOR WHERE NUMERO_SALA = 101;
SELECT COUNT(*) AS total_professores102 FROM SALA_PROFESSOR WHERE NUMERO_SALA = 102;
SELECT QUANTIDADE_ATUAL FROM SALA WHERE NUMERO_SALA=101;
SELECT QUANTIDADE_ATUAL FROM SALA WHERE NUMERO_SALA=102;