SET TRANSACTION ISOLATION LEVEL READ COMMITTED;DELETE FROM ALUNO WHERE IDADE_ALUNO > 25 AND NUMERO_SALA = 101;
DELETE FROM ALUNO WHERE IDADE_ALUNO > 25 AND NUMERO_SALA = 102;
DELETE FROM PROFESSOR WHERE DISCIPLINA_PROFESSOR = 'FÍSICA' AND NUMERO_SALA = 101;
DELETE FROM PROFESSOR WHERE DISCIPLINA_PROFESSOR = 'FÍSICA' AND NUMERO_SALA = 102;